{
 "title": "Price monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Количество запросов в минуту",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(main_app_predictions_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время выполнения предсказания",
   "type": "gauge",
   "description": "на 5 минутном интервале",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(main_app_prediction_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Трафик",
   "type": "timeseries",
   "description": "количество HTTP-запросов в секунду к значимой странице сервиса",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее количество запросов",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Медиана предсказаний за последние 5 минут",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(main_app_predictions_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.05, sum(rate(main_app_predictions_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(main_app_predictions_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}